import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const model=createRequire(import.meta.url)('../server/tally.js');
const cfg={title:'相談会',description:'',template:'custom',rows:[{id:'r1',label:'午前',active:true}],columns:[{id:'c1',label:'月曜',active:true},{id:'c2',label:'火曜',active:true}]};
const clone=x=>structuredClone(x);
test('追加したマスは既存回答者について未回答',()=>{const r=model.tally(cfg,[{id:'p1',name:'山田',selected:['r1:c1'],answered:['r1:c1']}]);assert.equal(r.cells['r1:c1'].count,1);assert.deepEqual(r.cells['r1:c2'].unknown,['p1']);assert.deepEqual(r.best,['r1:c1']);});
test('往復なぞりは再反転せず元配列も保持',()=>{const original=[];const a=model.beginStroke(original,'r1:c1');const b=model.visitStroke(a,'r1:c2');assert.deepEqual(model.visitStroke(b,'r1:c1').selected,['r1:c1','r1:c2']);assert.deepEqual(a.selected,['r1:c1']);assert.deepEqual(original,[]);});
test('解除なぞりを通過先に適用',()=>{const a=model.beginStroke(['r1:c1','r1:c2'],'r1:c1');assert.deepEqual(model.visitStroke(a,'r1:c2').selected,[]);});
test('UMDブラウザとNodeで有効マスが一致',()=>{const ctx={};vm.runInNewContext(fs.readFileSync(new URL('../server/tally.js',import.meta.url),'utf8'),ctx);assert.equal(JSON.stringify(ctx.TallyModel.activeCells(cfg)),JSON.stringify(['r1:c1','r1:c2']));});
const template=extra=>{let n=0;return model.makeTemplate({kind:'calendar',startDate:'2028-02-29',days:2,start:'09:00',end:'10:00',step:60,...extra},p=>p+(++n));};
test('うるう日と年末の繰越',()=>{assert.match(template({}).config.columns[1].label,/3\/1/);assert.match(template({startDate:'2026-12-31'}).config.columns[1].label,/1\/1/);});
for(const [label,input] of [['存在しない日',{startDate:'2026-02-29'}],['端数',{end:'10:15'}],['逆転',{end:'08:00'}],['日数超過',{days:32}],['未知間隔',{step:15}],['時刻不正',{start:'25:00'}]])test('カレンダーが'+label+'を拒否',()=>assert.equal(template(input).ok,false));
test('30分区切りと24時までの48行',()=>{const r=template({start:'00:00',end:'24:00',step:30});assert.equal(r.config.rows.length,48);assert.equal(r.config.rows[47].label,'23:30–24:00');});
test('時間割の昼休みと土日',()=>{let n=0;const r=model.makeTemplate({kind:'timetable',periods:10,lunch:true,weekend:true},p=>p+(++n));assert.equal(r.config.columns.length,7);assert.equal(r.config.rows.length,11);assert.equal(r.config.rows[2].label,'昼休み');});
test('自由な表の初期軸',()=>{let n=0;assert.equal(model.makeTemplate({kind:'custom'},p=>p+(++n)).config.rows.length,2);});
test('正規化で欠けた既存軸を非表示として保持',()=>{const edit=clone(cfg);edit.columns=edit.columns.slice(1);const r=model.normalizeBoard(edit,cfg);assert.equal(r.ok,true);assert.deepEqual(r.config.columns[1],{id:'c1',label:'月曜',active:false});});
test('改名と並べ替えでもIDは維持',()=>{const edit=clone(cfg);edit.columns.reverse();edit.columns[0].label='新しい火曜';const r=model.normalizeBoard(edit,cfg);assert.equal(r.ok,true);assert.deepEqual(model.activeCells(r.config),['r1:c2','r1:c1']);});
for(const [label,mutate] of [['空件名',x=>x.title=' '],['長い説明',x=>x.description='a'.repeat(2001)],['空軸名',x=>x.rows[0].label=' '],['重複ID',x=>x.columns[1].id='c1'],['不正ID',x=>x.rows[0].id='r:1'],['全行非表示',x=>x.rows[0].active=false],['列上限',x=>x.columns=Array.from({length:32},(_,i)=>({id:'c'+i,label:'列',active:true}))]])test('表で'+label+'を拒否',()=>{const x=clone(cfg);mutate(x);assert.equal(model.normalizeBoard(x).ok,false);});
test('保存後のテンプレート変更拒否',()=>assert.equal(model.normalizeBoard({...cfg,template:'calendar'},cfg).ok,false));
test('非表示も上限に含める',()=>{const old=clone(cfg);old.columns=Array.from({length:31},(_,i)=>({id:'c'+i,label:'列',active:i===0}));const next={...old,columns:[{id:'new',label:'追加',active:true}]};assert.equal(model.normalizeBoard(next,old).ok,false);});
test('回答の重複マスを除きansweredは現行全マス',()=>{const r=model.normalizeResponse({name:' 山田 ',note:'',selected:['r1:c1','r1:c1'],answered:[]},cfg);assert.deepEqual(r.data,{name:'山田',note:'',selected:['r1:c1'],answered:['r1:c1','r1:c2']});});
for(const [label,input] of [['未知マス',{name:'山田',selected:['r9:c1']}],['過大配列',{name:'山田',selected:Array(1489).fill('r1:c1')}],['空名',{name:' ',selected:[]}],['長いコメント',{name:'山田',note:'a'.repeat(501),selected:[]}]])test('回答が'+label+'を拒否',()=>assert.equal(model.normalizeResponse(input,cfg).ok,false));
test('全マス不可の回答も人数に含め最大0人にbestなし',()=>{const p={id:'p',selected:[],answered:['r1:c1','r1:c2']};const r=model.tally(cfg,[p]);assert.equal(r.total,1);assert.deepEqual(r.best,[]);assert.deepEqual(r.cells['r1:c1'].no,['p']);});
test('同名別ID、同率best、フィルター対象なし',()=>{const people=[{id:'p1',name:'山田',selected:['r1:c1'],answered:['r1:c1','r1:c2']},{id:'p2',name:'山田',selected:['r1:c2'],answered:['r1:c1','r1:c2']}];assert.deepEqual(model.tally(cfg,people).best,['r1:c1','r1:c2']);assert.equal(model.tally(cfg,people,[]).total,0);assert.deepEqual(model.tally(cfg,people,[]).best,[]);assert.deepEqual(model.tally(cfg,people,['p2']).best,['r1:c2']);});
test('非表示のマスは集計から外す',()=>{const x=clone(cfg);x.columns[1].active=false;assert.deepEqual(Object.keys(model.tally(x,[]).cells),['r1:c1']);});

// OPStappyの新規テンプレート。保存済みの旧テンプレートは変更しない。
test('Tappy形式は短い日付と終了時刻そのものを候補へ含める',()=>{const r=template({style:'tappy',startDate:'2026-12-31',start:'09:00',end:'11:00'});assert.deepEqual(r.config.columns.map(x=>x.label),['12/31','1/1']);assert.deepEqual(r.config.rows.map(x=>x.label),['09:00','10:00','11:00']);});
test('Tappy時間割は英語曜日と数字のコマ、末尾に昼休み',()=>{let n=0;const r=model.makeTemplate({kind:'timetable',style:'tappy',periods:3,lunch:true,weekend:true},p=>p+(++n));assert.deepEqual(r.config.columns.map(x=>x.label),['Mon','Tue','Wed','Thu','Fri','Sat','Sun']);assert.deepEqual(r.config.rows.map(x=>x.label),['1','2','3','昼休み']);});
test('Tappy形式でも30分・24時の上限超過を拒否して保存可能な軸だけを作る',()=>assert.equal(template({style:'tappy',start:'00:00',end:'24:00',step:30}).ok,false));
